##############################
# Metadata for pip/setuptools
##############################

[metadata]
name = moviepy
version = 2.2.0
description = Video editing with Python
author = Zulko 2025
license = MIT

[options]
packages = find:
python_requires = >=3.9
install_requires =
    decorator>=4.0.2,<6.0
    imageio>=2.5,<3.0
    imageio_ffmpeg>=0.2.0
    numpy>=1.25.0
    proglog<=1.0.0
    python-dotenv>=0.10
    pillow>=9.2.0
    opencv-python-headless>=4.0.0

[options.packages.find]
include = moviepy*
exclude =
    media
    tests
    docs

##############################
# Linting and style settings
##############################

[flake8]
max-line-length = 88
extend-ignore =
    E203,
    W503,
    E731,
    D104,
    D105,
    D205,
    D400,
    D401,
    D412,
    RST902,
    F403, F405
per-file-ignores =
    moviepy/editor.py: E402, F403, F405
    moviepy/version.py: D100
    moviepy/audio/fx/*.py: D100
    moviepy/video/fx/*.py: D100
    tests/*.py: D101,D102,D103
    examples/*.py: D100, F403, F405
docstring-convention = numpy

[isort]
profile = black
lines_after_imports = 2
combine_as_imports = True
py_version = 39
known_tests_third_party = pytest
sections = STDLIB,THIRDPARTY,TESTS_THIRD_PARTY,FIRSTPARTY,LOCALFOLDER

[coverage:report]
exclude_lines =
    pragma: no cover
